packages:
  - apps/*
  - packages/*

catalogMode: strict
cleanupUnusedCatalogs: true
engineStrict: true
minimumReleaseAge: 1440

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - core-js
  - esbuild
  - protobufjs
  - sharp
  - tree-sitter
  - tree-sitter-bash
  - workerd

catalog:
  '@antfu/eslint-config': ^5.4.1
  '@eslint/compat': ^1.2.5
  '@eslint/js': ^9.18.0
  '@fontsource-variable/manrope': ^5.2.6
  '@internationalized/date': ^3.8.1
  '@lucide/svelte': ^0.545.0
  '@sveltejs/adapter-node': 5.3.2
  '@sveltejs/kit': ^2.37.0
  '@sveltejs/vite-plugin-svelte': ^6.1.3
  '@tailwindcss/forms': 0.5.10
  '@tailwindcss/typography': 0.5.18
  '@tailwindcss/vite': 4.1.13
  '@tanstack/svelte-query': ^6.0.0
  '@tanstack/svelte-query-devtools': ^6.0.0
  '@tanstack/svelte-table': 9.0.0-alpha.10
  '@types/node': ^22.15.32
  '@typescript-eslint/parser': ^8.46.0
  arktype: ^2.1.20
  bits-ui: 2.8.10
  clsx: 2.1.1
  concurrently: ^9.1.2
  date-fns: ^4.1.0
  drizzle-arktype: ^0.1.3
  drizzle-kit: ^0.31.4
  drizzle-orm: ^0.44.3
  eslint: ^9.36.0
  eslint-config-prettier: ^10.1.5
  eslint-plugin-format: ^1.0.1
  eslint-plugin-svelte: ^3.10.1
  globals: ^16.0.0
  mode-watcher: ^1.0.8
  nanoid: ^5.1.5
  oxlint: ^1.19.0
  oxlint-tsgolint: ^0.2.0
  package-manager-detector: ^1.3.0
  paneforge: ^1.0.0-next.5
  prettier: ^3.6.2
  prettier-plugin-svelte: ^3.4.0
  prettier-plugin-tailwindcss: ^0.6.14
  runed: ^0.31.1
  svelte: ^5.38.6
  svelte-check: ^4.2.1
  svelte-eslint-parser: ^1.3.2
  svelte-sonner: ^1.0.5
  tailwind-merge: ^3.3.1
  tailwind-variants: ^3.1.1
  tailwindcss: ^4.1.11
  turbo: ^2.3.3
  tw-animate-css: ^1.3.5
  typescript: ^5.7.3
  typescript-eslint: ^8.20.0
  vaul-svelte: 1.0.0-next.7
  vite: ^7.0.5
  wellcrafted: ^0.22.0
  zod: ^3.25.74
